language: python

install:
  - pip install -r requirements.txt

script:
  - cd docs
  # Use Sphinx to make the html docs
  - make html

  - touch build/html/.nojekyll

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local-dir: docs/build/html
